window.ERA_DATA = {

  C: {
    bg:"#0F1115", bg2:"#1A1D24", bg3:"#2A2F3A",
    border:"#3A4150", text:"#E5E7EB", muted:"#6B7280",
    corpo:"#EF4444", mente:"#22D3EE", alma:"#A78BFA",
    gold:"#FDE68A", green:"#4ADE80"
  },

  TIERS: ["Leigo","Treinado","Especialista","Mestre","Maestria"],
  TIER_DT: [null, 4, 5, 6, 7],

  PILARS: {
    corpo:{ label:"CORPO", color:"#EF4444", subs:["forca","constituicao","destreza"] },
    mente:{ label:"MENTE", color:"#22D3EE", subs:["intelecto","sabedoria","vontade"] },
    alma: { label:"ALMA",  color:"#A78BFA", subs:["poder","dominio","afinidade"] },
  },

  SUBS: {
    forca:       { label:"Força",        abbr:"FOR" },
    constituicao:{ label:"Constituição", abbr:"CON" },
    destreza:    { label:"Destreza",     abbr:"DES" },
    intelecto:   { label:"Intelecto",    abbr:"INT" },
    sabedoria:   { label:"Sabedoria",    abbr:"SAB" },
    vontade:     { label:"Vontade",      abbr:"VON" },
    poder:       { label:"Poder",        abbr:"POD" },
    dominio:     { label:"Domínio",      abbr:"DOM" },
    afinidade:   { label:"Afinidade",    abbr:"AFI" },
  },

  LEVELS: [
    {l:1, hp:50,  sp:24,  pe:15},
    {l:2, hp:63,  sp:30,  pe:19},
    {l:3, hp:79,  sp:38,  pe:24},
    {l:4, hp:98,  sp:47,  pe:30},
    {l:5, hp:123, sp:59,  pe:37},
    {l:6, hp:153, sp:74,  pe:47},
    {l:7, hp:192, sp:92,  pe:58},
    {l:8, hp:239, sp:115, pe:73},
    {l:9, hp:299, sp:144, pe:91},
    {l:10,hp:374, sp:180, pe:114},
    {l:11,hp:468, sp:225, pe:142},
  ],

  CONDS: [
    {id:"envenenado", label:"Envenenado",  color:"#4ADE80", desc:"1d6 HP/turno · −1 Corpo · Antídoto/Lux"},
    {id:"sangrando",  label:"Sangrando",   color:"#EF4444", desc:"3 HP/turno · Primeiros socorros (u)"},
    {id:"imobilizado",label:"Imobilizado", color:"#F97316", desc:"Sem mover · −2 Destreza · Força DT 6 p/ sair"},
    {id:"atordoado",  label:"Atordoado",   color:"#FACC15", desc:"Perde Ação Maior próx. turno · Auto: 1 turno"},
    {id:"cego",       label:"Cego",        color:"#9CA3AF", desc:"Ataques c/ desvantagem · Inimigos c/ vantagem"},
    {id:"amedrontado",label:"Amedrontado", color:"#C084FC", desc:"Afasta da fonte · −2 tudo · Vontade DT 5/turno"},
    {id:"queimando",  label:"Queimando",   color:"#FB923C", desc:"1d6 fogo/turno · Ação para apagar ou água"},
    {id:"congelado",  label:"Congelado",   color:"#67E8F9", desc:"Imobilizado · Próx. ataque físico +1d6 · 2 turnos"},
    {id:"confuso",    label:"Confuso",     color:"#D946EF", desc:"Alvo aleatório 1d4/turno · Vontade DT 6"},
  ],

  DMG_COLS: ["+0","+1–2","+3–5","+6–9","+10–14","+15+"],
  DMG_ROWS: [
    {tier:"Leigo",    vals:["1d6","1d10","2d8","3d8","4d8","5d8"]},
    {tier:"Treinado", vals:["1d10","2d8","3d8","4d8","5d8","6d8"]},
    {tier:"Esp.",     vals:["2d8","3d8","4d8","5d8","6d8","8d8"]},
    {tier:"Mestre",   vals:["3d8","4d8","5d8","6d8","8d8","10d8"]},
    {tier:"Maestria", vals:["4d8","5d8","6d8","8d8","10d8","12d8+"]},
  ],

  WEAPONS: [
    {name:"Ataque Desarmado",   dmg:"1d4",      type:"Impacto",     emp:"D",     act:"M",          crit:"Atordoado",         cat:"cacl"},
    {name:"Adaga",              dmg:"1d4",      type:"Perf.",        emp:"1M/D",  act:"u",          crit:"Vital",             cat:"cacl"},
    {name:"Rondel",             dmg:"1d6",      type:"Perf.",        emp:"1M",    act:"u",          crit:"Ignora RD leve",    cat:"cacl"},
    {name:"Kukri",              dmg:"1d6",      type:"Corte",        emp:"1M/D",  act:"u",          crit:"Sangramento",       cat:"cacl"},
    {name:"Cimitarra",          dmg:"1d8",      type:"Corte",        emp:"1M",    act:"M",          crit:"Desarmar",          cat:"cacl"},
    {name:"Cinquedea",          dmg:"1d8",      type:"Corte/Perf.",  emp:"1M",    act:"u",          crit:"Vital",             cat:"cacl"},
    {name:"Espada Vitoriana",   dmg:"1d10",     type:"Corte",        emp:"1M",    act:"M",          crit:"Desarme/Empurrão",  cat:"cacm"},
    {name:"Katana",             dmg:"1d8/2d4+2",type:"Corte",        emp:"1M/2M", act:"M",          crit:"Sangramento",       cat:"cacm"},
    {name:"Lança",              dmg:"1d8/2d4+2",type:"Perf.",        emp:"1M/2M", range:"2u", act:"M", crit:"Empurrar",       cat:"cacm"},
    {name:"Naginata",           dmg:"1d10",     type:"Corte",        emp:"2M",    range:"2u", act:"M", crit:"Desarme",        cat:"cacm"},
    {name:"Kusarigama",         dmg:"1d10/2d6", type:"Corte/Imp.",   emp:"1M/2M", range:"2u", act:"M", crit:"Puxar/Derrubar", cat:"cacm"},
    {name:"Espada Alexandrina", dmg:"1d12",     type:"Corte",        emp:"2M",    act:"M+u",        crit:"Derrubar/Fragilizar",pen:"−2/0",cat:"cacp"},
    {name:"Odachi",             dmg:"2d8",      type:"Corte",        emp:"2M",    act:"M+u",        crit:"Derrubar+Fragilizar",pen:"−3",  cat:"cacp"},
    {name:"Machado de Guerra",  dmg:"2d8",      type:"Corte",        emp:"2M",    act:"M+u",        crit:"Sangramento",        pen:"−2",  cat:"cacp"},
    {name:"Martelo de Guerra",  dmg:"1d12",     type:"Impacto",      emp:"2M",    act:"M+u",        crit:"Fragilizar",         pen:"−2",  cat:"cacp"},
    {name:"Zweihander",         dmg:"2d6",      type:"Corte",        emp:"2M",    act:"M+u",        crit:"Empurrar+Fragilizar", pen:"−3", cat:"cacp"},
    {name:"Arco Curto",         dmg:"1d8",      type:"Perf.",        emp:"2M",    range:"6u",  act:"M / rec: u",  crit:"Imobilizar",      cat:"dist"},
    {name:"Arco Longo",         dmg:"1d10",     type:"Perf.",        emp:"2M",    range:"10u", act:"M / rec: u",  crit:"Perf. profunda",  cat:"dist"},
    {name:"Balestra",           dmg:"1d12",     type:"Perf.",        emp:"2M",    range:"8u",  act:"M / rec: M",  crit:"Fragilizar",      cat:"dist"},
    {name:"Revólver",           dmg:"1d8",      type:"Perf.",        emp:"1M",    range:"12u", act:"u / rec: M",  crit:"Vital",           cat:"dist"},
    {name:"Pistola",            dmg:"1d8",      type:"Perf.",        emp:"1M",    range:"10u", act:"u / rec: u",  crit:"Vital",           cat:"dist"},
    {name:"Rifle de Assalto",   dmg:"1d10",     type:"Perf.",        emp:"2M",    range:"20u", act:"M / semi-auto",crit:"Perf. profunda", cat:"dist"},
    {name:"Sniper",             dmg:"2d10",     type:"Perf.",        emp:"2M",    range:"40u+",act:"C / mira néc.",crit:"Abater",         cat:"dist"},
  ],

  ARMORS: [
    {name:"Couro Simples",    type:"Leve",   rd:"6",  pen:"−1 esquiva"},
    {name:"Couro Batido",     type:"Leve",   rd:"8",  pen:"−1 esq · −1 furt"},
    {name:"Arm. de Caçador",  type:"Leve",   rd:"8",  pen:"−2 esq · dist −5%"},
    {name:"Cota de Malha",    type:"Média",  rd:"12", pen:"−3 esq · −2 furt"},
    {name:"Brigandina",       type:"Média",  rd:"14", pen:"−3 esq · −2 fís"},
    {name:"Cota de Escamas",  type:"Média",  rd:"16", pen:"−4 esq · −1 des"},
    {name:"Placas Parcial",   type:"Pesada", rd:"22", pen:"−6 esq · −2 des"},
    {name:"Placas Completa",  type:"Pesada", rd:"26", pen:"−8 esq · −3 des"},
    {name:"Guerra Reforçada", type:"Pesada", rd:"30", pen:"−10 esq · −4 des"},
  ],

  ELEMENTOS: [
    {name:"Pyro",    pe:1, desc:"Fogo, calor, ignição"},
    {name:"Hydro",   pe:1, desc:"Água, pressão hidráulica"},
    {name:"Geo",     pe:1, desc:"Terra, barreiras"},
    {name:"Aero",    pe:1, desc:"Vento, dispersão"},
    {name:"Lux",     pe:1, desc:"Luz, purificação"},
    {name:"Umbra",   pe:1, desc:"Sombra, entropia"},
    {name:"Cryo",    pe:2, desc:"Frio intenso, gelo"},
    {name:"Electro", pe:2, desc:"Eletricidade, magnetismo"},
    {name:"Plantae", pe:2, desc:"Crescimento, venenos naturais"},
    {name:"Vita",    pe:3, desc:"Energia vital, regeneração"},
    {name:"Sonus",   pe:3, desc:"Som, vibração"},
    {name:"Nebula",  pe:3, desc:"Névoa etérea"},
    {name:"Inanis",  pe:3, desc:"Vazio, negação"},
    {name:"Ferrum",  pe:4, desc:"Metal, magnetismo"},
    {name:"Fulgaris",pe:4, desc:"Relâmpago massivo"},
    {name:"Noctis",  pe:4, desc:"Escuridão perceptual"},
    {name:"Tempus",  pe:4, desc:"Eco temporal (narrativo)"},
    {name:"Aposis",  pe:6, desc:"Dissolução entrópica"},
    {name:"Oblivion",pe:6, desc:"Apaga impressões de Névoa"},
  ],

  FORMAS: [
    {name:"Bola",       pe:1, desc:"Projétil 8u, ponto único"},
    {name:"Lâmina",     pe:1, desc:"Corte em arco, 2u"},
    {name:"Fio",        pe:1, desc:"Linha fina 6u"},
    {name:"Nuvem",      pe:1, desc:"Área difusa 2u raio"},
    {name:"Parede",     pe:1, desc:"Barreira 2u×4u"},
    {name:"Cone",       pe:2, desc:"Leque 90°, 4u"},
    {name:"Cúpula",     pe:2, desc:"Hemisfério 3u raio"},
    {name:"Barreira",   pe:2, desc:"Parede 4u×2u a distância"},
    {name:"Esfera",     pe:3, desc:"Bolha 2u raio"},
    {name:"Arm. Parcial",pe:4,desc:"RD +8 elemental"},
    {name:"Totem",      pe:4, desc:"Raio 3u, 2 PE/turno"},
    {name:"Runas",      pe:4, desc:"Ativa por gatilho"},
    {name:"Portal",     pe:5, desc:"Conexão entre pontos"},
    {name:"Invocação",  pe:5, desc:"Entidade temp. (Afin. Esp.+)"},
  ],

  PROPS: [
    {name:"Pesado",     pe:1, desc:"Crítico derruba"},
    {name:"Frio",       pe:1, desc:"+1 nív. Congelamento"},
    {name:"Calor",      pe:1, desc:"+1 nív. Queimadura"},
    {name:"Silencioso", pe:1, desc:"Furtividade intacta"},
    {name:"Afiado",     pe:1, desc:"Ignora 1 RD leve"},
    {name:"Dureza",     pe:2, desc:"+50 PV estruturas"},
    {name:"Velocidade", pe:2, desc:"+1 DT p/ esquivar"},
    {name:"Elétrico",   pe:2, desc:"+1d6 arm. metálica"},
    {name:"Magnético",  pe:2, desc:"Atrai/repele metais"},
    {name:"Venenoso",   pe:3, desc:"Envenenado 1"},
    {name:"Perfurante", pe:3, desc:"Ignora 5 RD"},
    {name:"Explosivo",  pe:3, desc:"50% dano raio 2u"},
    {name:"Paralisante",pe:3, desc:"Vontade DT 5 ou Atordoado"},
    {name:"Dreno de PE",pe:5, desc:"1d6 PE por acerto"},
  ],

  ACOES: [
    {sym:"M",   name:"Ação Maior",        desc:"Ataque médio/pesado, manifestação completa e interações complexas"},
    {sym:"u",   name:"Ação de Utilidade", desc:"Manifestação simples (1–3 PE), sacar arma, usar item, primeiros socorros"},
    {sym:"mov", name:"Movimento",         desc:"4 + Prog. Destreza unidades. Manifestação avançada (4–5 PE)"},
    {sym:"R",   name:"Reação",            desc:"1/rodada. Esquiva, bloqueio, contra-ataque, interceptação"},
    {sym:"C",   name:"Ação Completa",     desc:"Consome M + u + mov. Manifestação extrema (8+ PE)"},
  ],

  DT_TABLE: [
    {dt:4, grau:"Fácil",        auto:"Treinado+"},
    {dt:5, grau:"Moderado",     auto:"Especialista+"},
    {dt:6, grau:"Difícil",      auto:"Mestre+"},
    {dt:7, grau:"Extremo",      auto:"Maestria"},
    {dt:8, grau:"Sobrehumano",  auto:"Estigma ativo"},
    {dt:9, grau:"Transcendente",auto:"Pilar 5 + conds"},
  ],

};
