/*
 * Audit refactor:
 * - Documents that this file is declarative ERA rules/data consumed by the app.
 * - No mechanics, terminology, labels, tables, or numeric values are changed here.
 * - Global export is intentionally preserved for the current Babel/browser script stack.
 */
window.ERA_DATA = {

  C: {
    bg:"#0F1115", bg2:"#1A1D24", bg3:"#2A2F3A",
    border:"#3A4150", text:"#E5E7EB", muted:"#6B7280",
    corpo:"#DC2626", mente:"#36B7C8", alma:"#A78BFA",
    gold:"#FDE68A", green:"#7EA391"
  },

  TIERS: ["Leigo","Treinado","Especialista","Mestre","Lenda"],
  APT_SYMBOLS: ["○","◎","◆","❖","✦"],
  TIER_DT: [null, null, null, null, null],

  PILARS: {
    corpo:{ label:"FISICO", abbr:"PH", color:"#DC2626", base:1, subs:["forca","constituicao","destreza"] },
    mente:{ label:"MENTE",  abbr:"MD", color:"#36B7C8", base:1, subs:["intelecto","sabedoria","vontade"] },
    alma: { label:"ALMA",   abbr:"SL", color:"#A78BFA", base:0, subs:["poder","dominio","sintonia"] },
  },

  SUBS: {
    forca:        { label:"Forca",        abbr:"STR", desc:"Potencia muscular" },
    constituicao: { label:"Constituicao", abbr:"CON", desc:"Resistencia" },
    destreza:     { label:"Destreza",     abbr:"DEX", desc:"Agilidade" },
    intelecto:    { label:"Intelecto",    abbr:"INT", desc:"Inteligencia" },
    sabedoria:    { label:"Sabedoria",    abbr:"WIS", desc:"Experiencia pratica" },
    vontade:      { label:"Vontade",      abbr:"WLL", desc:"Determinacao" },
    poder:        { label:"Poder",        abbr:"PWR", desc:"Intensidade" },
    dominio:      { label:"Dominio",      abbr:"DOM", desc:"Controle" },
    sintonia:     { label:"Sintonia",     abbr:"SNT", desc:"Sensibilidade" },
  },

  LEVELS: [
    {l:1,  hp:24, sp:100, pe:12},
    {l:2,  hp:31, sp:100, pe:25},
    {l:3,  hp:38, sp:100, pe:38},
    {l:4,  hp:46, sp:100, pe:51},
    {l:5,  hp:53, sp:100, pe:65},
    {l:6,  hp:60, sp:100, pe:78},
    {l:7,  hp:67, sp:100, pe:91},
    {l:8,  hp:74, sp:100, pe:104},
    {l:9,  hp:82, sp:100, pe:117},
    {l:10, hp:89, sp:100, pe:131},
    {l:11, hp:96, sp:100, pe:144},
  ],

  APT_DIFFS: [
    {diff:"+1 APT", effect:"+2 PGE"},
    {diff:"+2 APT", effect:"+2 PGE e Vantagem"},
    {diff:"+3 APT", effect:"Sucesso automatico"},
    {diff:"-1 APT", effect:"-2 PGE"},
    {diff:"-2 APT", effect:"-2 PGE e Desvantagem"},
    {diff:"-3 APT", effect:"Falha automatica"},
  ],

  RECOVERY: [
    {resource:"HP", value:"12 + 1/4 do HP maximo"},
    {resource:"SP", value:"2#d6 + Nivel"},
    {resource:"PE", value:"3/4 do PE maximo"},
  ],

  OVERDRAFT: [
    {grade:"Nenhum", limit:"0", exhaustion:"Exausto 1", rest:"Normal"},
    {grade:"Leve", limit:"1/10 do total", exhaustion:"Exausto 2", rest:"Recupera apenas 1/2"},
    {grade:"Moderado", limit:"1/3 do total", exhaustion:"Exausto 3", rest:"Descanso Longo normal"},
    {grade:"Severo", limit:"1/2 do total", exhaustion:"Exausto 4", rest:"Sem recuperacao"},
  ],

  TRAUMAS: [
    {group:"Fisico", grade:"Leve", trigger:"HP < 1/4 do maximo", effect:"-1 em testes de Fisico"},
    {group:"Fisico", grade:"Grave", trigger:"3/4 do HP maximo em um unico hit", effect:"-2 em todos os testes; deslocamento 1/2"},
    {group:"Mental", grade:"1", trigger:"SP < 75", effect:"-1 em testes de Mente"},
    {group:"Mental", grade:"2", trigger:"SP < 50", effect:"-2 em Mente; -1 em Fisico e Alma"},
    {group:"Mental", grade:"3", trigger:"SP < 25", effect:"-3 em todos os testes"},
    {group:"Mental", grade:"4", trigger:"SP < 1", effect:"Insano, inconsciente ou morto"},
    {group:"Especial", grade:"Fobia", trigger:"Gatilho narrativo", effect:"-1 acumulativo contra a fonte do medo"},
    {group:"Especial", grade:"Trauma de Combate", trigger:"Experiencia de quase morte", effect:"Desvantagem em Iniciativa por 1d4 sessoes"},
    {group:"Especial", grade:"Estigma", trigger:"SL acima de 0", effect:"Pre-requisito narrativo para Alma acima de 0"},
  ],

  EXHAUSTION: [
    {grade:1, state:"Cansado", effect:"-1 em todas as rolagens"},
    {grade:2, state:"Esgotado", effect:"-2 em todas as rolagens"},
    {grade:3, state:"Exausto", effect:"-3 em tudo; deslocamento 1/2; sem recuperacoes"},
    {grade:4, state:"Colapso", effect:"Inconsciente; PE zerado"},
    {grade:5, state:"Morte", effect:"Morte"},
  ],

  CONDS: [
    {id:"queimando1", label:"Queimadura 1", color:"#B91C1C", desc:"Curas -50%; -1 em testes fisicos."},
    {id:"queimando2", label:"Queimadura 2", color:"#991B1B", desc:"Curas -75%; -2 fisicos; possivel limitacao do membro afetado."},
    {id:"queimando",  label:"Carbonizado",  color:"#7F1D1D", desc:"Membro inutilizado; -4 ou mais fisicos; curas -90% permanente."},
    {id:"sangrando",  label:"Sangramento 1", color:"#EF4444", desc:"1 dano por turno; cessa em 3 turnos ou com primeiros socorros; -1 resistencia/concentracao."},
    {id:"sangrando2", label:"Sangramento 2", color:"#DC2626", desc:"2-4 dano por turno; nao cessa naturalmente; -2 fisicos, esquiva e concentracao."},
    {id:"hemorragia", label:"Sangramento 3 - Hemorragia", color:"#991B1B", desc:"5-10% do HP maximo por turno; com HP <25% testa para nao cair; sem tratamento pode matar."},
    {id:"congelado1", label:"Congelamento 1", color:"#0891B2", desc:"Deslocamento e mobilidade -1 a -2; -1 ataque e esquiva."},
    {id:"congelado2", label:"Congelamento 2", color:"#0E7490", desc:"1-3 dano por turno; curas -50% a -75%; -2 fisicos/coordenacao."},
    {id:"congelado",  label:"Congelamento 3", color:"#155E75", desc:"Totalmente imobilizado; tratamento urgente para evitar morte."},
    {id:"fragilizado",  label:"Fragilizado 1", color:"#F59E0B", desc:"+25% dano recebido; -2 resistencia fisica e mental."},
    {id:"fragilizado2", label:"Fragilizado 2", color:"#D97706", desc:"+50% dano recebido; -3 resistencia fisica/mental; deslocamento -2."},
    {id:"fragilizado3", label:"Fragilizado 3", color:"#B45309", desc:"+75% dano recebido; -4 fisicos e mentais; deslocamento -3."},
    {id:"envenenado",  label:"Envenenado 1", color:"#7A8B63", desc:"1-3 dano por turno."},
    {id:"envenenado2", label:"Envenenado 2", color:"#647A45", desc:"4-6 dano por turno; -1 testes fisicos."},
    {id:"envenenado3", label:"Envenenado 3", color:"#4D6331", desc:"7-10 dano por turno; -2 testes fisicos e mentais."},
    {id:"toxina", label:"Toxina", color:"#365314", desc:"2-5% do HP maximo por turno crescente; -3 ou mais fisicos/mentais; exige antidoto."},
    {id:"infectado1", label:"Infectado 1", color:"#65A30D", desc:"-1 a -2 resistencia fisica/mental; dano leve por turno; pode transmitir."},
    {id:"infectado2", label:"Infectado 2", color:"#4D7C0F", desc:"-3 fisicos e mentais; dano progressivo; alto risco de transmissao."},
    {id:"infectado3", label:"Infectado 3", color:"#3F6212", desc:"-5 em quase tudo; dano grave continuo; pode perder controle; sem intervencao mata."},
    {id:"enfraquecido1", label:"Enfraquecido 1", color:"#A16207", desc:"-1 forca/ataques fisicos; dano causado -10%."},
    {id:"enfraquecido2", label:"Enfraquecido 2", color:"#854D0E", desc:"-3 forca, resistencia e ataques fisicos; dano -20% a -30%."},
    {id:"enfraquecido3", label:"Enfraquecido 3", color:"#713F12", desc:"-5 fisicos; dano -50%; deslocamento 1/2; risco de perder consciencia."},
    {id:"desidratado1", label:"Desidratado/Faminto 1", color:"#BFA14A", desc:"-1 resistencia fisica e forca."},
    {id:"desidratado2", label:"Desidratado/Faminto 2", color:"#B45309", desc:"-2 a -3 testes fisicos e mentais."},
    {id:"desidratado3", label:"Desidratado/Faminto 3", color:"#7C2D12", desc:"-5 em todos os testes; confusao; risco de inconsciencia; sem tratamento mata."},
    {id:"imobilizado", label:"Imobilizado", color:"#6B7280", desc:"Nao pode se deslocar ou fugir; acoes sem movimento ainda possiveis; -2 testes."},
    {id:"paralisado", label:"Paralisado", color:"#A78BFA", desc:"Incapaz de agir fisicamente; vulneravel; pode tentar resistencia mental para recuperar mobilidade."},
    {id:"atordoado", label:"Atordoado", color:"#FCD34D", desc:"Inabilitado por pelo menos 1 turno; penalidade maxima fisica e mental."},
    {id:"caido", label:"Caido", color:"#8A6A52", desc:"Defesa reduzida ate levantar; levantar custa acao menor."},
    {id:"desarmado", label:"Desarmado", color:"#9CA3AF", desc:"Arma caiu a 1u; recuperar custa acao menor + movimento."},
    {id:"assustado", label:"Assustado", color:"#A78BFA", desc:"-2 ataque, resistencia fisica e mental; iniciativa e deslocamento -1 por turno."},
    {id:"apavorado", label:"Apavorado", color:"#B45309", desc:"-4 em todos os testes; so pode fugir ou se proteger; sem rota pode paralisar."},
    {id:"desorientado", label:"Desorientado", color:"#36B7C8", desc:"-1 a -2 percepcao, iniciativa e ataques; dificuldade de mover em linha reta."},
    {id:"enlouquecido", label:"Enlouquecido", color:"#8B5CF6", desc:"-3 resistencia mental, ataque e defesa; pode agir impulsivamente contra aliados."},
    {id:"insano", label:"Insano", color:"#6D28D9", desc:"Falha automatica em resistencia mental; acoes imprevisiveis; comunicacao coerente impossivel."},
    {id:"entorpecido", label:"Entorpecido", color:"#94A3B8", desc:"-1 agilidade, concentracao e iniciativa; temporario e reversivel."},
    {id:"drogado1", label:"Drogado 1", color:"#64748B", desc:"-3 testes fisicos e mentais; alteracoes comportamentais."},
    {id:"drogado2", label:"Drogado 2", color:"#475569", desc:"-5 em quase todos os testes; possiveis alucinacoes, perda motora ou coma leve."},
    {id:"cego1", label:"Cegueira 1", color:"#9CA3AF", desc:"-1 a -2 precisao/percepcao visual; alcance visual -25%."},
    {id:"cego2", label:"Cegueira 2", color:"#6B7280", desc:"-3 ataques a distancia; -2 defesa fora de contato; percepcao visual falha."},
    {id:"cego", label:"Cegueira 3 - Total", color:"#4B5563", desc:"Falha automatica em tudo que exija visao; combate a distancia impossivel."},
    {id:"surdo1", label:"Surdo 1", color:"#38BDF8", desc:"-1 a -2 percepcao auditiva e sociais com comunicacao oral essencial."},
    {id:"surdo2", label:"Surdo 2", color:"#0284C7", desc:"Falha em audicao fina; -3 iniciativa/alerta; -2 sociais."},
    {id:"surdo", label:"Surdo 3 - Total", color:"#075985", desc:"Falha automatica em tudo baseado em audicao; comunicacao verbal impossivel sem auxilio."},
    {id:"silenciado1", label:"Silenciado 1", color:"#6B7280", desc:"Incapaz de falar ou emitir sons; componentes verbais bloqueados."},
    {id:"silenciado", label:"Silenciado 2", color:"#4B5563", desc:"Perda vocal; sons nao verbais possiveis; -2 sociais de comunicacao; verbais bloqueados."},
    {id:"mudo", label:"Mudo", color:"#374151", desc:"Perda definitiva da fala; exige comunicacao alternativa permanente."},
    {id:"vulneravel", label:"Vulneravel", color:"#FB7185", desc:"+50% dano recebido; -1 defesa/esquiva; maior suscetibilidade a condicoes negativas."},
    {id:"estado-critico", label:"Estado Critico", color:"#FCA5A5", desc:"Dano pode ser letal ou dobrado; -4 ou mais defesa/esquiva; exige estabilizacao."},
    {id:"amaldicoado1", label:"Amaldicoado 1", color:"#A78BFA", desc:"-1 testes variados; ma sorte leve."},
    {id:"amaldicoado2", label:"Amaldicoado 2", color:"#8B5CF6", desc:"-2 ou mais em testes importantes; possivel perda gradual de HP; reacao social negativa."},
    {id:"amaldicoado3", label:"Amaldicoado 3", color:"#6D28D9", desc:"-3 a -5 em quase tudo; possiveis deformidades; dificil de reverter."},
    {id:"enfeiticado", label:"Enfeiticado", color:"#A78BFA", desc:"Nao pode atacar ou agir contra a fonte; fonte recebe +10 sociais; cessa com hostilidade."},
    {id:"dominado", label:"Dominado", color:"#8B5CF6", desc:"Pode ser compelido por ordens da fonte; penalidade em WLL contra outros efeitos mentais."},
    {id:"charm", label:"Charm", color:"#6D28D9", desc:"Controle total da vontade; age como subordinado direto; desgaste progressivo."},
    {id:"assombro1", label:"Assombro 1", color:"#8B5CF6", desc:"Atacante recupera 10% do dano causado como HP; desvantagem WLL contra medo/mental."},
    {id:"assombro2", label:"Assombro 2", color:"#7C3AED", desc:"Atacante recupera 20%; alvo sofre 1d4 sombra no inicio do turno; desvantagem WLL."},
    {id:"assombro3", label:"Assombro 3", color:"#6D28D9", desc:"Atacante recupera 30%; alvo sofre 2d6 sombra; cura magica bloqueada; WLL falha automaticamente."},
  ],

  DMG_COLS: ["+0","+1-2","+3-5","+6-9","+10-14","+15+"],
  DMG_ROWS: [
    {tier:"Leigo",       vals:["1d6","1d8","2d6","2d8","3d8","4d8"]},
    {tier:"Treinado",    vals:["1d8","2d6","2d8","3d8","4d8","5d8"]},
    {tier:"Especialista",vals:["2d6","2d8","3d8","4d8","5d8","6d8"]},
    {tier:"Mestre",      vals:["2d8","3d8","4d8","5d8","6d8","8d8"]},
    {tier:"Lenda",       vals:["3d8","4d8","5d8","6d8","8d8","10d8"]},
  ],

  WEAPONS: [
    {name:"Ataque Desarmado",   dmg:"1d4",      type:"Impacto",     emp:"D",     act:"M",          crit:"Atordoado",         cat:"cacl"},
    {name:"Adaga",              dmg:"1d4",      type:"Perfuracao",   emp:"1M/D",  act:"m",          crit:"Vital",             cat:"cacl"},
    {name:"Rondel",             dmg:"1d6",      type:"Perfuracao",   emp:"1M",    act:"m",          crit:"Ignora RD leve",    cat:"cacl"},
    {name:"Kukri",              dmg:"1d6",      type:"Corte",        emp:"1M/D",  act:"m",          crit:"Sangramento",       cat:"cacl"},
    {name:"Cimitarra",          dmg:"1d8",      type:"Corte",        emp:"1M",    act:"M",          crit:"Desarmar",          cat:"cacl"},
    {name:"Cinquedea",          dmg:"1d8",      type:"Corte/Perf.",  emp:"1M",    act:"m",          crit:"Vital",             cat:"cacl"},
    {name:"Espada Vitoriana",   dmg:"1d10",     type:"Corte",        emp:"1M",    act:"M",          crit:"Desarme/Empurrao",  cat:"cacm"},
    {name:"Katana",             dmg:"1d8/2d4+2",type:"Corte",        emp:"1M/2M", act:"M",          crit:"Sangramento",       cat:"cacm"},
    {name:"Lanca",              dmg:"1d8/2d4+2",type:"Perfuracao",   emp:"1M/2M", range:"2u", act:"M", crit:"Empurrar",       cat:"cacm"},
    {name:"Naginata",           dmg:"1d10",     type:"Corte",        emp:"2M",    range:"2u", act:"M", crit:"Desarme",        cat:"cacm"},
    {name:"Kusarigama",         dmg:"1d10/2d6", type:"Corte/Imp.",   emp:"1M/2M", range:"2u", act:"M", crit:"Puxar/Derrubar", cat:"cacm"},
    {name:"Espada Alexandrina", dmg:"1d12",     type:"Corte",        emp:"2M",    act:"M+m",        crit:"Derrubar/Fragilizar",pen:"-2/0",cat:"cacp"},
    {name:"Odachi",             dmg:"2d8",      type:"Corte",        emp:"2M",    act:"M+m",        crit:"Derrubar+Fragilizar",pen:"-3",  cat:"cacp"},
    {name:"Machado de Guerra",  dmg:"2d8",      type:"Corte",        emp:"2M",    act:"M+m",        crit:"Sangramento",        pen:"-2",  cat:"cacp"},
    {name:"Martelo de Guerra",  dmg:"1d12",     type:"Impacto",      emp:"2M",    act:"M+m",        crit:"Fragilizar",         pen:"-2",  cat:"cacp"},
    {name:"Zweihander",         dmg:"2d6",      type:"Corte",        emp:"2M",    act:"M+m",        crit:"Empurrar+Fragilizar", pen:"-3", cat:"cacp"},
    {name:"Arco Curto",         dmg:"1d8",      type:"Perfuracao",   emp:"2M",    range:"6u",  act:"M / rec: m",  crit:"Imobilizar",      cat:"dist"},
    {name:"Arco Longo",         dmg:"1d10",     type:"Perfuracao",   emp:"2M",    range:"10u", act:"M / rec: m",  crit:"Perf. profunda",  cat:"dist"},
    {name:"Balestra",           dmg:"1d12",     type:"Perfuracao",   emp:"2M",    range:"8u",  act:"M / rec: M",  crit:"Fragilizar",      cat:"dist"},
    {name:"Revolver",           dmg:"1d8",      type:"Perfuracao",   emp:"1M",    range:"12u", act:"m / rec: M",  crit:"Vital",           cat:"dist"},
    {name:"Pistola",            dmg:"1d8",      type:"Perfuracao",   emp:"1M",    range:"10u", act:"m / rec: m",  crit:"Vital",           cat:"dist"},
    {name:"Rifle de Assalto",   dmg:"1d10",     type:"Perfuracao",   emp:"2M",    range:"20u", act:"M / semi-auto",crit:"Perf. profunda", cat:"dist"},
    {name:"Sniper",             dmg:"2d10",     type:"Perfuracao",   emp:"2M",    range:"40u+",act:"C / mira nec.",crit:"Abater",         cat:"dist"},
  ],

  ARMORS: [
    {name:"Pele Nua",          type:"Sem armadura", rd:"0",  pen:"Sem penalidade"},
    {name:"Couro Simples",     type:"Leve",         rd:"6",  pen:"-1 esquiva"},
    {name:"Couro Batido",      type:"Leve",         rd:"8",  pen:"-1 esq; -1 furt"},
    {name:"Arm. de Cacador",   type:"Leve",         rd:"8",  pen:"-2 esq; dist -5%"},
    {name:"Cota de Malha",     type:"Media",        rd:"12", pen:"-3 esq; -2 furt"},
    {name:"Brigandina",        type:"Media",        rd:"14", pen:"-3 esq; -2 fis"},
    {name:"Cota de Escamas",   type:"Media",        rd:"16", pen:"-4 esq; -1 des"},
    {name:"Placas Parcial",    type:"Pesada",       rd:"22", pen:"-6 esq; -2 des"},
    {name:"Placas Completa",   type:"Pesada",       rd:"26", pen:"-8 esq; -3 des"},
    {name:"Guerra Reforcada",  type:"Pesada",       rd:"30", pen:"-10 esq; -4 des"},
  ],

  DAMAGE_TYPE_RULES: [
    {type:"Impacto", naked:"Normal", light:"Normal", medium:"-1 RD ef.", heavy:"+1 dado de dano", crit:"Atordoado; pode derrubar"},
    {type:"Corte", naked:"Normal", light:"Normal", medium:"Normal", heavy:"-1 RD ef.", crit:"Sangramento"},
    {type:"Perfuracao", naked:"Normal", light:"Ignora 3 RD", medium:"Ignora 3 RD", heavy:"Normal", crit:"+1 dado de dano"},
    {type:"Lacerante", naked:"+1 dado de dano", light:"+1 dado de dano", medium:"Normal", heavy:"-1 dado de dano", crit:"Sangramento Grave"},
  ],

  ELEMENTOS: [
    {name:"Pyro", pe:1, desc:"Fogo, calor, ignicao"},
    {name:"Hydro", pe:1, desc:"Agua, pressao hidraulica"},
    {name:"Geo", pe:1, desc:"Terra, barreiras"},
    {name:"Aero", pe:1, desc:"Vento, dispersao"},
    {name:"Lux", pe:1, desc:"Luz, purificacao"},
    {name:"Umbra", pe:1, desc:"Sombra, entropia"},
    {name:"Cryo", pe:2, desc:"Frio intenso, gelo"},
    {name:"Electro", pe:2, desc:"Eletricidade, magnetismo"},
    {name:"Plantae", pe:2, desc:"Crescimento, venenos naturais"},
    {name:"Vita", pe:3, desc:"Energia vital, regeneracao"},
    {name:"Sonus", pe:3, desc:"Som, vibracao"},
    {name:"Nebula", pe:3, desc:"Nevoa eterea"},
    {name:"Inanis", pe:3, desc:"Vazio, negacao"},
    {name:"Ferrum", pe:4, desc:"Metal, magnetismo"},
    {name:"Fulgaris", pe:4, desc:"Relampago massivo"},
    {name:"Noctis", pe:4, desc:"Escuridao perceptual"},
    {name:"Tempus", pe:4, desc:"Eco temporal narrativo"},
    {name:"Aposis", pe:6, desc:"Dissolucao entropica"},
    {name:"Oblivion", pe:6, desc:"Apaga impressoes de Nevoa"},
  ],

  FORMAS: [
    {name:"Bola", pe:1, desc:"Projetil 8u, ponto unico"},
    {name:"Lamina", pe:1, desc:"Corte em arco, 2u"},
    {name:"Fio", pe:1, desc:"Linha fina 6u"},
    {name:"Nuvem", pe:1, desc:"Area difusa 2u raio"},
    {name:"Parede", pe:1, desc:"Barreira 2u x 4u"},
    {name:"Cone", pe:2, desc:"Leque 90 graus, 4u"},
    {name:"Cupula", pe:2, desc:"Hemisferio 3u raio"},
    {name:"Barreira", pe:2, desc:"Parede 4u x 2u a distancia"},
    {name:"Esfera", pe:3, desc:"Bolha 2u raio"},
    {name:"Arm. Parcial", pe:4, desc:"RD +8 elemental"},
    {name:"Totem", pe:4, desc:"Raio 3u, 2 PE/turno"},
    {name:"Runas", pe:4, desc:"Ativa por gatilho"},
    {name:"Portal", pe:5, desc:"Conexao entre pontos"},
    {name:"Invocacao", pe:5, desc:"Entidade temp. (Especialista+)"},
  ],

  PROPS: [
    {name:"Pesado", pe:1, desc:"Critico derruba"},
    {name:"Frio", pe:1, desc:"+1 nivel Congelamento"},
    {name:"Calor", pe:1, desc:"+1 nivel Queimadura"},
    {name:"Silencioso", pe:1, desc:"Furtividade intacta"},
    {name:"Afiado", pe:1, desc:"Ignora 1 RD leve"},
    {name:"Dureza", pe:2, desc:"+50 PV estruturas"},
    {name:"Velocidade", pe:2, desc:"+1 DT p/ esquivar"},
    {name:"Eletrico", pe:2, desc:"+1d6 arm. metalica"},
    {name:"Magnetico", pe:2, desc:"Atrai/repele metais"},
    {name:"Venenoso", pe:3, desc:"Envenenado 1"},
    {name:"Perfurante", pe:3, desc:"Ignora 5 RD"},
    {name:"Explosivo", pe:3, desc:"50% dano raio 2u"},
    {name:"Paralisante", pe:3, desc:"WLL DT 5 ou Atordoado"},
    {name:"Dreno de PE", pe:5, desc:"1d6 PE por acerto"},
  ],

  ACOES: [
    {sym:"M",  name:"Acao Maior",    desc:"Acao principal: ataques, Manifestacoes Completas e interacoes complexas."},
    {sym:"m",  name:"Acao Menor",    desc:"Acao rapida: Manifestacoes Simples (1-3 keywords), sacar arma ou usar item."},
    {sym:"Mv", name:"Movimento",     desc:"Deslocamento base (4 + Progresso Destreza). Manifestacoes Avancadas (4-7 keywords)."},
    {sym:"R",  name:"Reacao",        desc:"Esquiva, bloqueio ou contra-ataque. So se perceber a acao."},
    {sym:"L",  name:"Livre",         desc:"Acoes verbais curtas e declaracoes. Ilimitado quando fizer sentido."},
    {sym:"C",  name:"Acao Completa", desc:"Consome o turno inteiro. Manifestacoes Extremas (15+ keywords)."},
  ],

  DT_TABLE: [
    {dt:4, grau:"Facil", apt:"Leigo", note:"Pressao baixa; referencia inicial."},
    {dt:5, grau:"Moderado", apt:"Treinado", note:"Exige algum treino ou boa PGE."},
    {dt:6, grau:"Dificil", apt:"Especialista", note:"Tarefa tecnica ou arriscada."},
    {dt:7, grau:"Extremo", apt:"Mestre", note:"Apenas maestria ou vantagem clara sustenta."},
    {dt:8, grau:"Sobrehumano", apt:"Lenda", note:"Limite humano/paranormal elevado."},
    {dt:9, grau:"Transcendente", apt:"Lenda+", note:"Cena excepcional; mestre define ancoras."},
  ],

  COMBAT_SEQUENCE: [
    {step:"1", action:"Declare ataque e alvo", detail:"Informe arma ou Manifestacao."},
    {step:"2", action:"Subatributo de acerto", detail:"STR para pesadas CaC; DEX para leves/distancia; DOM para Manifestacoes."},
    {step:"3", action:"Role PILAR d6 + PGE", detail:"Use sempre o melhor dado. Total contra a defesa do alvo."},
    {step:"4", action:"Alvo rola defesa", detail:"DEX antecipado; WIS->DEX veloz; automatico em surpresa."},
    {step:"5", action:"Role dano", detail:"Dano bruto da arma, rolado duas vezes; pegue o melhor."},
    {step:"6", action:"Aplique dano", detail:"Subtraia RD, reduza HP e aplique condicoes se necessario."},
  ],

  DODGE_REACTIONS: [
    {margin:"Falha -4", result:"Desvio catastrofico", effect:"Dano cheio + condicao severa + Abertura para o atacante"},
    {margin:"Falha -3", result:"Desvio quebrado", effect:"Dano cheio + Abertura para o atacante"},
    {margin:"Falha -2", result:"Desvio falho", effect:"Dano cheio"},
    {margin:"Falha -1", result:"Desvio parcial", effect:"Metade do dano"},
    {margin:"Sucesso 0", result:"Desvio mediano", effect:"1/4 do dano"},
    {margin:"Sucesso +1", result:"Desvio solido", effect:"Escapa sem dano"},
    {margin:"Sucesso +2", result:"Desvio firme", effect:"Escapa + reposicionamento favoravel"},
    {margin:"Sucesso +3", result:"Desvio perfeito", effect:"Escapa + Abertura"},
  ],

  PARRY_REACTIONS: [
    {margin:"Falha -4", result:"Aparada catastrofica", effect:"Dano cheio + condicao severa + possivel dano na arma/membro"},
    {margin:"Falha -3", result:"Aparada quebrada", effect:"Dano cheio + Abertura para o atacante"},
    {margin:"Falha -2", result:"Aparada falha", effect:"Dano cheio"},
    {margin:"Falha -1", result:"Aparada parcial", effect:"Mitiga 1/4 do dano"},
    {margin:"Sucesso 0", result:"Aparada mediana", effect:"Mitiga metade do dano"},
    {margin:"Sucesso +1", result:"Aparada solida", effect:"Mitiga 3/4 do dano"},
    {margin:"Sucesso +2", result:"Aparada firme", effect:"Mitiga dano cheio"},
    {margin:"Sucesso +3", result:"Aparada perfeita", effect:"Mitiga tudo + Abertura"},
  ],

  SANITY_LOSS: [
    {source:"Contundente / Perfurante / Cortante", loss:"1 SP", note:"Todo dano fisico abala a integridade corporal."},
    {source:"Lacerante / Queimadura", loss:"2 SP", note:"Dano mais traumatico."},
    {source:"Area critica com dano critico ou quebra", loss:"5-15 SP", note:"Criterio do mestre."},
    {source:"Trauma severo", loss:"10-40 SP", note:"Teste de Sanidade pode mitigar."},
    {source:"Perda critica unica", loss:"40+ SP", note:"Surto psicotico, paralisia mental ou perda temporaria de controle social/mental."},
  ],

  CONTROL_MANEUVERS: [
    {name:"Agarrar", cost:"m", test:"Forca vs Forca DT5", effect:"Imovel (ambos)"},
    {name:"Derrubar", cost:"m", test:"-", effect:"Caido; defesa reduzida ate levantar; liberar: acao menor"},
    {name:"Desarmar", cost:"m", test:"-", effect:"Arma cai a 1u; recuperar: m + Mv"},
    {name:"Empurrar", cost:"m", test:"-", effect:"Recua 1-3u conforme Tier de Forca"},
    {name:"Estrangular", cost:"M", test:"Req. Agarrar; liberar Forca DT5", effect:"1d6 de dano por turno"},
    {name:"Arremessar Objeto", cost:"M", test:"-", effect:"Queda + dano por distancia ate 10u"},
    {name:"Arremessar Pessoa", cost:"M", test:"STR + Manejo vs CON do alvo", effect:"Falha -2: 1 dado no lugar; Falha -1: 1u/2 dados; Sucesso 0: 2u/3 dados; +1: 3u/4 dados; +2: 4u/5 dados; +3: 5u/6 dados"},
  ],

  POSITIONING_RULES: [
    {name:"Altura superior", effect:"+1 dado de dano", method:"Escalar ou saltar"},
    {name:"Flanqueio", effect:"Vantagem", method:"Aliado no lado oposto"},
    {name:"Costas do alvo", effect:"Acerto automatico se o alvo nao souber da presenca", method:"Furtividade ou flanqueio"},
    {name:"Cobertura parcial", effect:"-1 DT para ser acertado", method:"Pilar, arvore, canto"},
    {name:"Solo dificil", effect:"-1 ataque e defesa fisicos", method:"Lama ou escombros"},
    {name:"Confinado <2u", effect:"Hastes sofrem Desvantagem", method:"Corredores estreitos"},
  ],

  LUCK_ROLL: [
    {roll:"1-3", result:"Azar", effect:"Complicacao narrativa imediata."},
    {roll:"4-6", result:"Neutro", effect:"Nada acontece."},
    {roll:"7-9", result:"Sorte", effect:"Vantagem imediata OU +2 de dano."},
    {roll:"10", result:"Grande Sorte", effect:"Efeito positivo significativo definido pelo Mestre."},
  ],

};
